# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://diary.t98.info/"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
publishDir = "docs"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

enableGitInfo = true

# googleAnalytics = ""

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
